// import localFont from "next/font/local";
// import "./globals.css";
// import { SessionProvider } from "next-auth/react";
// import Nav from "./components/Nav";
// import Footer from "./components/Footer";
// import { auth } from "@/auth";
// import Glitter from "./components/Glitter";
// import ScrollHandler from "./components/ScrollHandler";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({ children }) {
//   const session = await auth();
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <SessionProvider>
         
//           <div className="fixed top-0 left-0 right-0 z-50">
//             <Nav server_session_data={session} />
//           </div>
//           <div id="glitter-component" className=" z-999 transition-transform duration-300 ease-in-out">
//             <Glitter />
//           </div>
//           <ScrollHandler />
//           <div className="pt-32"> {/* Adjust this value based on the combined height of Glitter and Nav */}
//             {children}
//           </div>
//           <Footer />
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }







import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import {auth } from "@/auth"
import Glitter from "./components/Glitter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          {/* <Glitter/> */}
          <Nav server_session_data={session}></Nav>
         
        {children}
          <Footer/>
        </SessionProvider>
       
      </body>
    </html>
  );
}
