import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import {auth } from "@/auth"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <Nav server_session_data={session}></Nav>
        {children}
          <Footer/>
        </SessionProvider>
       
      </body>
    </html>
  );
}
